train:
  _target_: src.datasets.AVSSDataset
  part: "train"
  instance_transforms: ${transforms.instance_transforms.train}
val:
  _target_: src.datasets.AVSSDataset
  part: "val"
  instance_transforms: ${transforms.instance_transforms.inference}
test:
  _target_: src.datasets.AVSSDataset
  part: "test"
  instance_transforms: ${transforms.instance_transforms.inference}
