train:
  _target_: src.datasets.AVSSDataset
  part: "train"
  embed_dir: "src/data/embeddings"
  instance_transforms: ${transforms.instance_transforms.train}
val:
  _target_: src.datasets.AVSSDataset
  part: "val"
  embed_dir: "src/data/embeddings"
  instance_transforms: ${transforms.instance_transforms.inference}
