_target_: src.model.AVDPTN
N: 64
L: 8
K: 151
H: 72
nhead: 4
dropout: 0.1
lstm_dim: 64
bidirectional: false
R: 6
C: 2
fusion_method: "linear"
audio_len: 7999
interpolation_mode: "linear"
d_model: 256
num_heads: 4
emb_dropout: 0.1
bidir: true
