_target_: src.model.AVConvTasNet
N: 512
L: 16
B: 128
Sc: 128
H: 512
P: 3
X: 8
R: 3
C: 2
fusion_method: 'gated'
audio_len: 3999 # не уверен
interpolation_mode: 'linear'
d_model: 256
num_heads: 4
emb_dropout: 0.1
bidir: False
