defaults:
  - model: baseline
  - writer: cometml
  - metrics: example
  - datasets: example
  - dataloader: example
  - transforms: example_only_instance
  - _self_
optimizer:
  _target_: torch.optim.AdamW
  lr: 0.0003
lr_scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  T_max: 10000
loss_function:
  _target_: src.loss.SI_SNR_Loss
trainer:
  log_step: 10
  n_epochs: 15
  epoch_len:
  grad_accum_steps: 4
  device_tensors: ['s1_spectrogram', 's2_spectrogram', 'mix_spectrogram', 's1_audio', 's2_audio', 'mix_audio', 's1_mouth', 's2_mouth'] # which tensors should be on device (ex. GPU)
  resume_from: 'checkpoint-epoch3.pth' # null or path to the checkpoint dir with *.pth and config.yaml
  device: auto # device name or "auto"
  override: True # if True, will override the previous run with the same name
  monitor: "off" # "off" or "max/min metric_name", i.e. our goal is to maximize/minimize metric
  save_period: 1 # checkpoint each save_period epochs in addition to the best epoch
  early_stop: ${trainer.n_epochs} # epochs for early stopping
  save_dir: "saved"
  seed: 1
  log_inference_every_n_epochs: 1
  max_grad_norm: 5.0
