defaults:
  - model: dptn_attn
  - writer: cometml
  - metrics: train_metrics
  - datasets: train_val
  - dataloader: a100
  - transforms: example_only_instance
  - _self_
optimizer:
  _target_: torch.optim.AdamW
  lr: 0.0003
lr_scheduler:
  _target_: src.scheduler.NoamLR
  model_size: 64
  warmup_steps: 1560
  factor: 1
loss_function:
  _target_: src.loss.SI_SNR_Loss_by_hand
trainer:
  log_step: 10
  n_epochs: 50
  epoch_len:
  grad_accum_steps: 1
  device_tensors: ['s1_spectrogram', 's2_spectrogram', 'mix_spectrogram', 's1_audio', 's2_audio', 'mix_audio', 's1_embs', 's2_embs'] # which tensors should be on device (ex. GPU)
  resume_from: # null or path to the checkpoint dir with *.pth and config.yaml
  device: auto # device name or "auto"
  override: True # if True, will override the previous run with the same name
  monitor: "off" # "off" or "max/min metric_name", i.e. our goal is to maximize/minimize metric
  save_period: 1 # checkpoint each save_period epochs in addition to the best epoch
  early_stop: ${trainer.n_epochs} # epochs for early stopping
  save_dir: "saved"
  seed: 1
  log_inference_every_n_epochs: 1
  max_grad_norm: 10.0
  # from_pretrained: "checkpoint-epoch16.pth"
